title: "Nathan Pennybaker"
name: "Nathan Pennybaker"
description: "Electrical Engineering Portfolio"
url: "https://natepenny.github.io"
baseurl: ""
repository: "natepenny/natepenny.github.io"

author:
  avatar: "profile.jpg"
  name: "Nathan Pennybaker"
  bio: "Electrical Engineering student at OU."
  location: "Norman, OK"
  employer: "University of Oklahoma"
  github: "natepenny"
  linkedin: "nathanpennybaker"

include:
  - _pages
  - files
exclude:
  - Gemfile
  - LICENSE
  - README
  - _teaching
  - _publications
  - _talks

collections:
  portfolio:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
